name: Webhook Logger

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, closed, synchronize]

jobs:
  send-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Log Webhook to MongoDB
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"action": "'${{ github.event_name }}'", "author": "'${{ github.actor }}'", "ref": "'${{ github.ref }}'", "timestamp": "'${{ github.event.head_commit.timestamp }}'"}' \
          https://efa6-154-160-23-153.ngrok-free.app/webhook/receiver