name: Trigger Webhook on Push and PR

on:
  push:
    branches:
      - '**'  # triggers on push to any branch
  pull_request:
    types: [opened, synchronize, closed]

jobs:
  notify-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Send webhook to Flask server
        run: |
          curl -X POST https://f86fa8275c89.ngrok-free.app/webhook/receiver \
          -H "Content-Type: application/json" \
          -H "X-GitHub-Event: ${{ github.event_name }}" \
          -d '{
            "author": "${{ github.actor }}",
            "ref": "${{ github.ref }}",
            "timestamp": "${{ github.event.head_commit.timestamp }}"
          }'